/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/shared/ui/button/Button.vue')['default']
    IconEye: typeof import('./src/shared/ui/icons/IconEye.vue')['default']
    IconEyeOff: typeof import('./src/shared/ui/icons/IconEyeOff.vue')['default']
    IconLogo: typeof import('./src/shared/ui/icons/IconLogo.vue')['default']
    IconQR: typeof import('./src/shared/ui/icons/IconQR.vue')['default']
    Input: typeof import('./src/shared/ui/input/Input.vue')['default']
    Logo: typeof import('./src/shared/ui/logo/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
