/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/shared/ui/avatar/Avatar.vue')['default']
    Button: typeof import('./src/shared/ui/button/Button.vue')['default']
    Cropper: typeof import('./src/shared/ui/cropper/Cropper.vue')['default']
    DialogClose: typeof import('./src/shared/ui/dialog/DialogClose.vue')['default']
    DialogOverlay: typeof import('./src/shared/ui/dialog/DialogOverlay.vue')['default']
    DialogPortal: typeof import('./src/shared/ui/dialog/DialogPortal.vue')['default']
    Drawer: typeof import('./src/shared/ui/drawer/ui/Drawer.vue')['default']
    FieldWrapper: typeof import('./src/shared/ui/form/FieldWrapper.vue')['default']
    IconCamera: typeof import('./src/shared/ui/icons/IconCamera.vue')['default']
    IconChevronLeft: typeof import('./src/shared/ui/icons/IconChevronLeft.vue')['default']
    IconEdit: typeof import('./src/shared/ui/icons/IconEdit.vue')['default']
    IconEye: typeof import('./src/shared/ui/icons/IconEye.vue')['default']
    IconEyeOff: typeof import('./src/shared/ui/icons/IconEyeOff.vue')['default']
    IconLogo: typeof import('./src/shared/ui/icons/IconLogo.vue')['default']
    IconLogoFull: typeof import('./src/shared/ui/icons/IconLogoFull.vue')['default']
    IconLogout: typeof import('./src/shared/ui/icons/IconLogout.vue')['default']
    IconMenu: typeof import('./src/shared/ui/icons/IconMenu.vue')['default']
    IconQR: typeof import('./src/shared/ui/icons/IconQR.vue')['default']
    IconUser: typeof import('./src/shared/ui/icons/IconUser.vue')['default']
    IconX: typeof import('./src/shared/ui/icons/IconX.vue')['default']
    Input: typeof import('./src/shared/ui/form/Input.vue')['default']
    Logo: typeof import('./src/shared/ui/logo/Logo.vue')['default']
    Modal: typeof import('./src/shared/ui/modal/ui/Modal.vue')['default']
    ProfileLayout: typeof import('./src/shared/ui/layouts/ProfileLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
